assert_lefthook_installed: true

pre-commit:
  parallel: true
  commands:
    eslint:
      glob: '*'
      run: npx eslint --cache --fix {staged_files}
      stage_fixed: true
    stylelint:
      glob: 'src/**.{css,scss,vue,tsx}'
      run: npx stylelint --fix {staged_files}
      stage_fixed: true
