// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./../components/Counter.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    ICarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    ICarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    ICarbonLanguage: typeof import('~icons/carbon/language')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    README: typeof import('./../components/README.md')['default']
  }
}

export { }
